### ISSUE TITLE
DDP is not working with Pytorch Lightning

### ISSUE THREAD

**Issue by bolandih** [Lightning-AI/lightning#10471]
I am using DDP in a single machine with 2 GPUs. when I am running the code it stuck forever with the below script. The code is working properly with dp and also with ddp using a single GPU.

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Using native 16bit precision.
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
Using native 16bit precision.
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2

To reproduce I used the boring code which exactly produce the above script:

```
import os
import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    # test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        gpus=2,
        distributed_backend='ddp',
    )
    trainer.fit(model, train_data, val_data)
    # trainer.test(model,test_data)

if __name__ == "__main__":
    run()
```
I ran the code with NCCL_DEBUG=INFO and raised with errors below:

```
u116642:82796:82796 [0] NCCL INFO Bootstrap : Using enp68s0:35.9.130.234<0>
u116642:82796:82796 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal
implementation
u116642:82796:82796 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
u116642:82796:82796 [0] NCCL INFO NET/Socket : Using [0]enp68s0:35.9.130.234<0>
[1]veth07bbc25:fe80::5897:33ff:fe5e:15ee%veth07bbc25<0>
[2]veth2d1e326:fe80::54c0:1cff:fe70:8b39%veth2d1e326<0>
u116642:82796:82796 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda11.3
u116642:82845:82845 [1] NCCL INFO Bootstrap : Using enp68s0:35.9.130.234<0>
u116642:82845:82845 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal
implementation
u116642:82845:82845 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
u116642:82845:82845 [1] NCCL INFO NET/Socket : Using [0]enp68s0:35.9.130.234<0>
[1]veth07bbc25:fe80::5897:33ff:fe5e:15ee%veth07bbc25<0>
[2]veth2d1e326:fe80::54c0:1cff:fe70:8b39%veth2d1e326<0>
u116642:82845:82845 [1] NCCL INFO Using network Socket
u116642:82796:82908 [0] NCCL INFO Channel 00/04 : 0 1
u116642:82845:82930 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1 [2] -1/-1/-1->1->0 [3]
0/-1/-1->1->-1
u116642:82796:82908 [0] NCCL INFO Channel 01/04 : 0 1
u116642:82796:82908 [0] NCCL INFO Channel 02/04 : 0 1
u116642:82796:82908 [0] NCCL INFO Channel 03/04 : 0 1
u116642:82796:82908 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1 [2] 1/-1/-1->0->-1 [3]
-1/-1/-1->0->1
u116642:82796:82908 [0] NCCL INFO Setting affinity for GPU 0 to ffff,ffffffff
u116642:82796:82908 [0] NCCL INFO Channel 00 : 0[1000] -> 1[21000] via P2P/IPC
u116642:82796:82908 [0] NCCL INFO Channel 01 : 0[1000] -> 1[21000] via P2P/IPC
u116642:82796:82908 [0] NCCL INFO Channel 02 : 0[1000] -> 1[21000] via P2P/IPC
u116642:82796:82908 [0] NCCL INFO Channel 03 : 0[1000] -> 1[21000] via P2P/IPC
u116642:82845:82930 [1] NCCL INFO Channel 00 : 1[21000] -> 0[1000] via P2P/IPC
u116642:82845:82930 [1] NCCL INFO Channel 01 : 1[21000] -> 0[1000] via P2P/IPC
u116642:82845:82930 [1] NCCL INFO Channel 02 : 1[21000] -> 0[1000] via P2P/IPC
u116642:82845:82930 [1] NCCL INFO Channel 03 : 1[21000] -> 0[1000] via P2P/IPC
u116642:82796:82908 [0] NCCL INFO Connected all rings
u116642:82796:82908 [0] NCCL INFO Connected all trees
u116642:82796:82908 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
u116642:82796:82908 [0] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
u116642:82845:82930 [1] NCCL INFO Connected all rings
u116642:82845:82930 [1] NCCL INFO Connected all trees
u116642:82845:82930 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
u116642:82845:82930 [1] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
u116642:82796:82908 [0] NCCL INFO comm 0x7f30ac002fb0 rank 0 nranks 2 cudaDev 0 busId 1000 -
Init COMPLETE
u116642:82796:82796 [0] NCCL INFO Launch mode Parallel

u116642:82845:82930 [1] NCCL INFO comm 0x7f8578002fb0 rank 1 nranks 2 cudaDev 1 busId 21000 -
Init COMPLETE
```

PyTorch Version :1.9
OS: Linux
PyTorch installed with pip
Python lightning version: 1.0.0
CUDA/cuDNN version: 11.4
GPU models and configuration: 2 GPU of A 6000

cc @tchaton @justusschock

**Comment by akihironitta** [comment]
@H-B-L `pytorch-lightning==1.0.0` is not tested against `torch==1.9` which I checked in the release tag: https://github.com/PyTorchLightning/pytorch-lightning/tree/1.0.0#continuous-integration.

In addition, `1.0.0` was released more than a year ago, and there are quite a number of bugfixes/improvements since then, so would you mind updating the version and giving it a try again? You can upgrade the version by running `pip install -U pytorch-lightning`.

**Comment by H-B-L** [comment]
I used the latest version of PyTorch lightning and has the same issue. The reason I used an old version of PyTorch lighting is that I want to run the code in Spyder, not in the terminal.  DDP in the latest versions should be run as a script in the terminal.

**Comment by carmocca** [comment]
Might be caused by

`u116642:82845:82845 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]`

Can you try running a barebones pure-pytorch DDP script? It doesn't seem to be caused by Lightning

**Comment by H-B-L** [comment]
I used the [Toy Model](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) to run with pure-PyTorch DDP script and there was no issue in DDP. It seems the problem is caused by DDP itself.

**Comment by pritamdamania87** [comment]
> Might be caused by

> u116642:82845:82845 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]

> Can you try running a barebones pure-pytorch DDP script? It doesn't seem to be caused by Lightning

This is probably a red herring and just means NCCL is not going to use ibverbs and would use TCP instead.

**Comment by awaelchli** [comment]
DDP stability has improved drastically and steadily in Lightning since 1.0. If you have to stay on 1.0.0 I recommend to try the latest bugfix release 1.0.8.

**Comment by H-B-L** [comment]
@awaelchli, I mentioned in my comment that I used the latest version of PyTorch lightning and still the problem exists.

**Comment by H-B-L** [comment]
@pritamdamania87, Any idea how to address this issue?

**Comment by akihironitta** [comment]
I couldn't reproduce the error with 2 GPUs on a single node:

<details><summary>details</summary>

```diff
-       distributed_backend='ddp',
+       strategy='ddp',
+       enable_model_summary=False,  # just for clean output
+       enable_progress_bar=False,  # just for clean output
```

```console
$ NCCL_DEBUG=INFO python script.py > nccl_debug.log 2> pl_output.log
$ cat nccl_debug.log
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34785 [0] NCCL INFO Bootstrap : Using eth0:10.0.110.85<0>
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34785 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34785 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34785 [0] NCCL INFO NET/Socket : Using [0]eth0:10.0.110.85<0>
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34785 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda11.3
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34791 [1] NCCL INFO Bootstrap : Using eth0:10.0.110.85<0>
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34791 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34791 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34791 [1] NCCL INFO NET/Socket : Using [0]eth0:10.0.110.85<0>
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34791 [1] NCCL INFO Using network Socket
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO Channel 00/02 :    0   1
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34805 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO Channel 01/02 :    0   1
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO Channel 00 : 0[1d0] -> 1[1e0] via direct shared memory
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34805 [1] NCCL INFO Channel 00 : 1[1e0] -> 0[1d0] via direct shared memory
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO Channel 01 : 0[1d0] -> 1[1e0] via direct shared memory
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34805 [1] NCCL INFO Channel 01 : 1[1e0] -> 0[1d0] via direct shared memory
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO Connected all rings
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO Connected all trees
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34805 [1] NCCL INFO Connected all rings
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34805 [1] NCCL INFO Connected all trees
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34805 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/512
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34805 [1] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34804 [0] NCCL INFO comm 0x7fbcc4002fb0 rank 0 nranks 2 cudaDev 0 busId 1d0 - Init COMPLETE
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34791:34805 [1] NCCL INFO comm 0x7fc304002fb0 rank 1 nranks 2 cudaDev 1 busId 1e0 - Init COMPLETE
ixnode-6f92c075-6f33-4a18-8d18-61841e571bfa-f6c76f47d-zkjh7:34785:34785 [0] NCCL INFO Launch mode Parallel
$ cat  pl_output.log
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
/home/jovyan/work/pytorch-lightning/pytorch_lightning/trainer/data_loading.py:110: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/jovyan/work/pytorch-lightning/pytorch_lightning/trainer/data_loading.py:406: UserWarning: The number of training samples (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
/home/jovyan/work/pytorch-lightning/pytorch_lightning/trainer/data_loading.py:110: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
[W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
$ wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/requirements/collect_env_details.py
$ python collect_env_details.py 
* CUDA:
        - GPU:
                - Tesla M60
                - Tesla M60
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.21.3
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.0
        - pytorch-lightning: 1.6.0dev
        - tqdm:              4.62.3
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.9.7
        - version:           #1 SMP Mon Sep 27 12:48:12 UTC 2021
```

</details>

@H-B-L Could you update the description of your environment by running the following commands?
```console
$ wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/requirements/collect_env_details.py
$ python collect_env_details.py 
```

**Comment by carmocca** [comment]
Have you tried with PyTorch 1.7 to 1.10? We don't have testing for 1.11 yet

**Comment by awaelchli** [comment]
> @awaelchli, I mentioned in my comment that I used the latest version of PyTorch lightning and still the problem exists.

That does not seem to be the case. The environment collection script still detects 1.0.8. It's right there in your post.

**Comment by H-B-L** [comment]
> > @awaelchli, I mentioned in my comment that I used the latest version of PyTorch lightning and still the problem exists.
> 
> That does not seem to be the case. The environment collection script still detects 1.0.8. It's right there in your post.
@awaelchli, First, I tested the latest version of PyTorch lightning and then since it did not solve the issue I returned back to version 1.0.8 and then run the command for environment collection.

**Comment by H-B-L** [comment]
Back to latest PyTorch lightning and switching the torch backend to 'gloo' from 'nccl' worked for me. But it seems 'gloo' backend is slower than 'nccl. Any other ideas to use 'nccl' without the issue? Seems PyTorch lightning has this issue for some specific GPUs. Bunch of users have the same problem. Check out the [#4612](https://github.com/PyTorchLightning/pytorch-lightning/issues/4612).

**Comment by tchaton** [comment]
Dear @H-B-L,

Have you tried using the base PyTorch Lightning image? And run your code within a docker image?

Best,
T.C

**Comment by H-B-L** [comment]
@tchaton, I didn't run the code within a docker image yet. I will try that.

**Comment by tchaton** [comment]
Hey @H-B-L,

You can try: pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.8

**Comment by leobxpan** [comment]
Any updates since? I'm having the same problem with pl==1.5.10 (latest) / 1.4.2 and with pytorch==1.7.1 / 1.8.0, cuda==11.1

**Comment by awaelchli** [comment]
I'm closing the issue now. Recent versions of Lightning work well with DDP, we haven't noticed similar reports from users. Since @bolandih mentioned NCCL had issues on their machine while GLOO was working, I would suggest anyone that finds this thread to look at the NCCL troubleshooting guide [here](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html).
