### ISSUE TITLE
CUDA out of memory After 74 epochs

### ISSUE THREAD

**Issue by ZwormZ** [Lightning-AI/lightning#12874]
## 🐛 Bug

I am using the pytorch-lighting to run on 8 V100GPUs，and I set a seed in my train srcipt, everything went well at beginning, but encountered  **CUDA out of memory** while running the 74th epoch. This  can be steadily reproduced since  I have run the experiment 4 times with the same result.  The detailed log information is posted in the Additional context section. 

### Expected behavior

It will be great if you can give me some suggestion! Thank you!

### Environment

- PyTorch Lightning Version : 1.3.0
- PyTorch Version : 1.7.1
- Python version : 3.8
- OS : Linux
- CUDA/cuDNN version:11.0
- GPU models and configuration: V100 32GB
- How you installed PyTorch (`conda`, `pip`, source): `conda`

### Additional context

![image](https://user-images.githubusercontent.com/52192467/165015733-3a7a2904-2cc0-47e3-b2eb-1c302098dfe8.png)

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7 @borda

**Comment by akihironitta** [comment]
@ZwormZ I believe there're quite a number of fixes/improvements since `1.3.0` released a year ago, so could you try a newer version? Also, if the problem still persists, would it be feasible for you to share a reproducible script?

**Comment by ZwormZ** [comment]
Thanks for replying to me!

I have update pytorch-lighting to 1.5.10 version, and try to run twcie. This time I encountered CUDA out of memory while running the second epoch. I have not encountered this when running smaller models, but when I try to deepen the model by one layer, this happens and instead of **CUDA out of memory** at the beginning of training, I get an error at some epoch, which I am confused about. 
After update, the detailed log information is posted in the Additional context section. 

Here is my boring model:

```
class BaseProteinModel(pl.LightningModule, ABC):
    def __init__(
        self,
        vocab: Vocab,
        optimizer_config: OptimizerConfig = OptimizerConfig(),
        contact_train_data: Optional[TRRosettaContactDataset] = None,
    ):
        super().__init__()
        self.vocab = vocab
        self.optimizer_config = optimizer_config

    @abstractmethod
    def forward(
        self, tokens
    ):
        return NotImplemented

    def training_step(self, batch, batch_idx):

        src, tgt = batch
        logits = self(src)["logits"]
        valid_mask = tgt != self.vocab.pad_idx
        logits = logits[valid_mask]
        tgt = tgt[valid_mask]

        loss = nn.CrossEntropyLoss(reduction="none")(logits, tgt)
        loss = loss.mean()
        self.log("train_loss", loss, prog_bar=True, on_epoch=True)

        return loss

    def validation_step(self, batch, batch_idx):
        src, tgt = batch
        logits = self(src)["logits"]
        valid_mask = tgt != self.vocab.pad_idx
        logits = logits[valid_mask]
        tgt = tgt[valid_mask]

        loss = nn.CrossEntropyLoss(reduction="none")(logits, tgt)
        loss = loss.mean()
        self.log("val_loss", loss, prog_bar=True, on_epoch=True)

        return loss

trainer = pl.Trainer(
        logger=logger,
        callbacks=[lr_logger, checkpoint_callback], 
        accumulate_grad_batches=1,
        accelerator="gpu",
        strategy=DDPPlugin(find_unused_parameters=True),
        fast_dev_run=False,
        gpus=8,
        gradient_clip_val=0,
        log_every_n_steps=50,
        max_epochs=1000,
        min_epochs=500,
        num_nodes=1,
        precision=32,
        progress_bar_refresh_rate=1,
        resume_from_checkpoint=None,
        track_grad_norm=-1,
    )

trainer.fit(model, train_dataloader=train_loader, val_dataloaders=valid_loader)
```


# Additional context
![image](https://user-images.githubusercontent.com/52192467/165434861-ff7b4c64-946f-4cb7-b100-80148657758a.png)

**Comment by justusschock** [comment]
Can you also add the implementation of `forward`? It seems this would be causing the error.

**Comment by ZwormZ** [comment]
Here is the  the implementation of `forward`:
During Training, parameter: repr_layers=None, need_head_weights=False, return_contacts=False
```
    def forward(
        self, tokens, repr_layers=[], need_head_weights=False, return_contacts=False
    ):
        if return_contacts:
            need_head_weights = True

        assert tokens.ndim == 3
        batch_size, num_alignments, seqlen = tokens.size()
        padding_mask = tokens.eq(self.vocab.pad_idx)  # B, R, C
        if not padding_mask.any():
            padding_mask = None
        x = self.embed_tokens(tokens.long())
        # x = self.embed_tokens(tokens)
        x += self.embed_positions(
            tokens.view(batch_size * num_alignments, seqlen)
        ).view(x.size())
        if self.msa_position_embedding is not None:
            if x.size(1) > 1024:
                raise RuntimeError(
                    "Using model with MSA position embedding trained on maximum MSA "
                    f"depth of 1024, but received {x.size(1)} alignments."
                )
            x += self.msa_position_embedding[:, :num_alignments]

        x = self.emb_layer_norm_before(x)

        x = self.dropout_module(x)

        if padding_mask is not None:
            x = x * (1 - padding_mask.unsqueeze(-1).type_as(x))

        repr_layers = set(repr_layers)
        hidden_representations = {}
        if 0 in repr_layers:
            hidden_representations[0] = x

        if need_head_weights:
            row_attn_weights = []
            col_attn_weights = []

        # B x R x C x D -> R x C x B x D
        x = x.permute(1, 2, 0, 3)

        for layer_idx, layer in enumerate(self.layers):
            x = layer(
                x,
                self_attn_padding_mask=padding_mask,
                need_head_weights=need_head_weights,
            )
            if need_head_weights:
                x, col_attn, row_attn = x
                # H x C x B x R x R -> B x H x C x R x R
                col_attn_weights.append(col_attn.permute(2, 0, 1, 3, 4))
                # H x B x C x C -> B x H x C x C
                row_attn_weights.append(row_attn.permute(1, 0, 2, 3))
            if (layer_idx + 1) in repr_layers:
                hidden_representations[layer_idx + 1] = x.permute(2, 0, 1, 3)

        x = self.emb_layer_norm_after(x)
        x = x.permute(2, 0, 1, 3)  # R x C x B x D -> B x R x C x D

        # last hidden representation should have layer norm applied
        if (layer_idx + 1) in repr_layers:
            hidden_representations[layer_idx + 1] = x
        x = self.lm_head(x)

        result = {"logits": x, "representations": hidden_representations}
        if need_head_weights:
            # col_attentions: B x L x H x C x R x R
            col_attentions = torch.stack(col_attn_weights, 1)
            # row_attentions: B x L x H x C x C
            row_attentions = torch.stack(row_attn_weights, 1)
            result["col_attentions"] = col_attentions
            result["row_attentions"] = row_attentions
            if return_contacts:
                contacts = self.contact_head(tokens, row_attentions)
                result["contacts"] = contacts

        return result

```

**Comment by yuhongyu0721** [comment]
I have the same issues. Anything updates? Thx

**Comment by akihironitta** [comment]
@yuhongyu0721 @ZwormZ Do you have a full script and env detail that reproduces the behaviour?

**Comment by yuhongyu0721** [comment]
> @yuhongyu0721 @ZwormZ Do you have a full script and env detail that reproduces the behaviour?

I figure out my problem is caused by Pytorch and its compilation. It's fixed by reinstall Pytorch with clean environment.
