### ISSUE TITLE
Fabric launch failed on TPU

### ISSUE THREAD

**Issue by Xingyu-Lin** [Lightning-AI/lightning#17194]
### Bug description

The program either hangs or throws out an error when launching a fabric object. Tested on a v2-8 TPU.

### How to reproduce the bug

```python
def main():
    import lightning as L
    fabric = L.Fabric(accelerator='tpu', devices=8)
    fabric.launch()
    print('fabric setup done')
    return

if __name__ == '__main__':
    main()
```

### Error messages and logs

```

WARNING:root:Unsupported nprocs (8), ignoring...
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/gcpuser/miniconda3/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/gcpuser/miniconda3/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/gcpuser/miniconda3/lib/python3.8/multiprocessing/queues.py", line 347, in __getstate__
    context.assert_spawning(self)
  File "/home/gcpuser/miniconda3/lib/python3.8/multiprocessing/context.py", line 359, in assert_spawning
    raise RuntimeError(
RuntimeError: SimpleQueue objects should only be shared between processes through inheritance
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./my_dino/test_fabric.py", line 10, in <module>
    train_dino()
  File "./my_dino/test_fabric.py", line 5, in train_dino
    fabric.launch()
  File "/home/gcpuser/miniconda3/lib/python3.8/site-packages/lightning/fabric/fabric.py", line 650, in launch
    return self._strategy.launcher.launch(function, *args, **kwargs)
  File "/home/gcpuser/miniconda3/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py", line 70, in launch
    xmp.spawn(
  File "/home/gcpuser/miniconda3/lib/python3.8/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 386, in spawn
    return pjrt.spawn(fn, nprocs, start_method, args)
  File "/home/gcpuser/miniconda3/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 365, in spawn
    _run_multiprocess(spawn_fn, start_method=start_method)
  File "/home/gcpuser/miniconda3/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 92, in wrapper
    return fn(*args, **kwargs)
  File "/home/gcpuser/miniconda3/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 322, in _run_multiprocess
    replica_results = list(
  File "/home/gcpuser/miniconda3/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 323, in <genexpr>
    itertools.chain.from_iterable(
  File "/home/gcpuser/miniconda3/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/gcpuser/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/gcpuser/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/gcpuser/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/gcpuser/miniconda3/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/gcpuser/miniconda3/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/gcpuser/miniconda3/lib/python3.8/multiprocessing/queues.py", line 347, in __getstate__
    context.assert_spawning(self)
  File "/home/gcpuser/miniconda3/lib/python3.8/multiprocessing/context.py", line 359, in assert_spawning
    raise RuntimeError(
RuntimeError: SimpleQueue objects should only be shared between processes through inheritance

```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component: Lightning fabric
#- PyTorch Lightning Version: 2.0.0
#- PyTorch Version: 2.0
#- Python version: 3.8
#- OS: Linux
#- CUDA/cuDNN version:
#- GPU models and configuration: tpu-v2-8, tpuvm
#- How you installed Lightnin: pip
#- Running environment of LightningApp: google cloud
```

</details>

cc @JackCaoG @steventk-g @Liyang90 @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
@Xingyu-Lin TPU only supports launching through spawning worker functions like so:

```py
def run_training(fabric):
    print('fabric training ...')


def main():
    import lightning as L
    fabric = L.Fabric(accelerator='tpu', devices=8)
    fabric.launch(run_training)
    

if __name__ == '__main__':
    main()
```

We will make a better error handling here and provide proper documentation with examples. Thanks for flagging!

**Comment by Xingyu-Lin** [comment]
Thanks for the prompt reply. However, the new code also does not work and yield the same error

**Comment by Liyang90** [comment]
Hi @Xingyu-Lin, have you set the XRT runtime config as stated here: https://lightning.ai/docs/pytorch/stable/accelerators/tpu_intermediate.html#tpu-vm?

**Comment by Xingyu-Lin** [comment]
Got it. It seems that the 2.0x version uses PJRT by default. As such, I downgrade to 1.12 and use XRT. This solution works for me now.

**Comment by Liyang90** [comment]
> Got it. It seems that the 2.0x version uses PJRT by default. As such, I downgrade to 1.12 and use XRT. This solution works for me now.

And just FYI, 2.0 is still supporting XRT mode if you set that env var, downgrade is not required :)
