### ISSUE TITLE
Fabric dataloaders die when num workers > 0 and distributed.

### ISSUE THREAD

**Issue by mileseverett** [Lightning-AI/lightning#17378]
### Bug description

When using fabric for distributed training using ddp or fsdp as strategy on two 1080ti or 2080ti, line of code:

```
for batch_idx, batch in enumerate(train_dataloader):
```

causes errors after a few epochs.

Full traceback:

```
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f4c648004d7 in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f4c647ca36b in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f4c648a4fa8 in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x135fe (0x7f4c648755fe in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x22d80 (0x7f4c64884d80 in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4ccea6 (0x7f4ca3d37ea6 in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3ee77 (0x7f4c647e5e77 in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x1be (0x7f4c647de69e in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #8: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f4c647de7b9 in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x752458 (0x7f4ca3fbd458 in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #10: THPVariable_subclass_dealloc(_object*) + 0x305 (0x7f4ca3fbd7e5 in /home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>

Traceback (most recent call last):
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miles/Programming/pl2f_error/src/main.py", line 137, in <module>
    main(args)
  File "/home/miles/Programming/pl2f_error/src/main.py", line 54, in main
    train(fabric, model, optimizer, train_dataloader, val_dataloader)
  File "/home/miles/Programming/pl2f_error/src/main.py", line 73, in train
    for batch_idx, batch in enumerate(train_dataloader):
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 178, in __iter__
    for item in self._dataloader:
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1295, in _get_data
    success, data = self._try_get_data()
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1157, in _try_get_data
    fs = [tempfile.NamedTemporaryFile() for i in range(fds_limit_margin)]
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1157, in <listcomp>
    fs = [tempfile.NamedTemporaryFile() for i in range(fds_limit_margin)]
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
  File "/home/miles/anaconda3/envs/pl2/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 727166) is killed by signal: Aborted. 
```

Minimal repo to reproduce issue: https://github.com/mileseverett/pl2f_error

By setting num_workers to 0 in main.py code will run fine, any num_workers > 0 has caused issues for me.

### What version are you seeing the problem on?

2.0+

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by carmocca** [comment]
Might be similar to the infamous https://github.com/Lightning-AI/torchmetrics/issues/1560. Although in your case, you aren't using `transformers`

cc @awaelchli

**Comment by awaelchli** [comment]
@mileseverett Does the problem fix itself if you remove all the torchmetrichs? (as observed in https://github.com/Lightning-AI/torchmetrics/issues/1560)?

**Comment by albertfgu** [comment]
I started encountering the same error message, with the same conditions: using `datasets`, DDP with `num_workers>0`. In my case I'm not using `torchmetrics` though. I've seen several related open issues, seems like the underlying problems are still unknown?

**Comment by awaelchli** [comment]
Yes, still unknown.

> I've seen several related open issues

Can you list them here please?

**Comment by albertfgu** [comment]
Actually, I think all the issues I found can be found from the linked torchmetrics thread. I had seen a bunch of other similar issues, but with slightly different CUDA errors or they were older issues from 1+ years ago, so I assume they probably aren't the same underlying problem.

Actually, I have a question about torchmetrics. I am actually not sure how Lightning accumulates metrics per epoch. For example, consider a simple example from the `LightningModule` documentation:
```
class Task(pl.LightningModule):

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self.model(x)
        loss = F.cross_entropy(y_hat, y)
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self.model(x)
        loss = F.cross_entropy(y_hat, y)
        metrics = {"val_loss": loss}
        self.log_dict(metrics)
        return metrics
```
I think with this example, Lightning does report an epoch average of the loss (e.g. `val_loss`; perhaps one also has to pass in `on_step=False, on_epoch=True` to `self.log_dict`).
However, how does Lightning ensure that the epoch metric is properly normalized across batches (say the last batch is smaller than the rest)?

I remember digging into this a long time ago and concluding that lightning was doing the right thing, but that was before torchmetrics were introduced. I also can't find the answer on a quick google search or skimming through the source code. I just want to make sure that it's not implicitly using torchmetrics somehow, in which case perhaps my issue is the same bug as the other thread you linked.

**Comment by albertfgu** [comment]
I don't know if this can possibly be related to this issue, but here's something else I've been getting. I downgraded from `lightning=2.1` to `pytorch-lightning=1.9.3` to see if it fixes these issues. My runs are no longer crashing in the same way, but I'm getting another error I've never seen before:
```
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f172e1d2b90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1462, in _shutdown_workers
    if w.is_alive():
  File "/usr/lib/python3.10/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception in thread QueueFeederThread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 239, in _feed
Exception in thread QueueFeederThread:
Traceback (most recent call last):
Exception in thread QueueFeederThread:
Traceback (most recent call last):
    reader_close()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 177, in close
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f172e1d2b90>
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 239, in _feed
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 239, in _feed
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._close()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 361, in _close
    self._shutdown_workers()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1462, in _shutdown_workers
    reader_close()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 177, in close
    if w.is_alive():
  File "/usr/lib/python3.10/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
    _close(self._handle)
    reader_close()
OSError: [Errno 9] Bad file descriptor
```

**Comment by albertfgu** [comment]
Another set of observations I observed for the original error:

- For a given run, the place it crashes seemed deterministic - down the same epoch and batch (although once I noticed the batch change by 1, which was strange)
- This made me think it could be something related to my particular dataset. However, small things that shouldn't affect data ordering also changed where the crash was. In particular, using the same run but adding WandbLogger would crash at a different epoch - but still deterministically (running the same command with wandb logging would always crash on the same epoch/step). I don't think that adding a WandbLogger would change the data ordering unless it affects random seed somehow, so this was very mysterious.

And just to be complete, this was the complete error I got:
```
Epoch 149: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  7.45it/s, v_num=0, trainer/loss=1.220, train/loss=1.220]Epoch 149, global step 1200: 'test/loss' was not in top 1
Epoch 150: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  7.50it/s, v_num=0, trainer/loss=1.220, train/loss=1.220]Epoch 150, global step 1208: 'test/loss' was not in top 1
Epoch 151:  50%|████████████████████████████████████████████████████████████▌                                                            | 4/8 [00:00<00:00,  5.63it/s, v_num=0, trainer/loss=1.220, train/loss=1.220]
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /opt/pytorch/pytorch/c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x7feb5baf803e in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7feb5babe1e9 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3f2 (0x7feb659dc6f2 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x1200c (0x7feb659ac00c in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x23e65 (0x7feb659bde65 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x459b5a (0x7feb1dda4b5a in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0xd (0x7feb5bad4f4d in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #7: <unknown function> + 0x7046e8 (0x7feb1e04f6e8 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #8: THPVariable_subclass_dealloc(_object*) + 0x2e6 (0x7feb1e04fa46 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x1283a7 (0x563d31f3f3a7 in /usr/bin/python3)
frame #10: <unknown function> + 0x153090 (0x563d31f6a090 in /usr/bin/python3)
frame #11: <unknown function> + 0x1531d0 (0x563d31f6a1d0 in /usr/bin/python3)
...
frame #63: _PyEval_EvalFrameDefault + 0x81b (0x563d31f5c8cb in /usr/bin/python3)

Epoch 151:  62%|███████████████████████████████████████████████████████████████████████████▋                                             | 5/8 [00:01<00:00,  4.12it/s, v_num=0, trainer/loss=1.220, train/loss=1.220]Error executing job with overrides: ['experiment=hg38/hg38_hyena', 'model.d_model=128', 'model.n_layer=2', 'dataset.batch_size=256', 'train.global_batch_size=256', 'dataset.max_length=1024', 'optimizer.lr=6e-4', 'trainer.max_steps=10000', 'trainer.devices=16', 'loader.num_workers=1', 'loader.pin_memory=false', 'wandb=null']
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 59454) is killed by signal: Aborted.

**Comment by awaelchli** [comment]
Here, someone wrote that they downgraded grpcio: https://github.com/Lightning-AI/torchmetrics/issues/1560#issuecomment-1515734923
Maybe worth a try.

**Comment by albertfgu** [comment]
I've tried that and it doesn't help unfortunately

**Comment by LWprogramming** [comment]
Also having this error and can confirm the `num_workers=0` prevents crashing

**Comment by RuABraun** [comment]
I got this error and also thought it was because of the dataloader for quite a while but it seems to be because of torchmetrics. Removing it fixed it for me.

**Comment by wzf03** [comment]
I encountered this error as well, and it turned out that torchmetrics was the culprit too.
I discovered that by attaching the metrics to the LightningModule and letting Lightning handle the movement to the GPU instead of manually managing it separately, the error magically disappeared!
It seems that because torchmetrics.Metric is actually a torch.nn.Module, it needs to be treated as such.
