### ISSUE TITLE
Calling `trainer.log_dir` in `rank_zero_only` with DDP makes the program freeze after first step

### ISSUE THREAD

**Issue by aRI0U** [Lightning-AI/lightning#18148]
### Bug description

When running a program on multi-GPU with DDP, if I call `trainer.log_dir` in the code, it mysteriously makes the code freeze after the first step. However this happens only when I call `trainer.log_dir` only in process 0, otherwise everything works as expected.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
import torch
from torch.utils.data import Dataset

import lightning.pytorch as pl
from lightning.pytorch.utilities import rank_zero_only


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    @rank_zero_only  # <-- THIS IS THE CRITICAL THING
    def on_fit_start(self) -> None:
        print(self.trainer.log_dir)

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(output)
        return loss

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(output)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


def run():
    train_data = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=0)
    val_data = torch.utils.data.DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=0)

    model = BoringModel()
    trainer = pl.Trainer(max_epochs=1, accelerator="gpu", strategy="ddp", devices=[1, 2])
    trainer.fit(model, train_data, val_data)


if __name__ == '__main__':
    print(pl.__version__)
    run()
```

### Error messages and logs

```
# Error messages and logs here please
```
Nothing, the code just get stuck and I have to manually type `kill -9 <pid>` to exit, ctrl+C doesn't work

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.2
#- PyTorch Version (e.g., 2.0): 2.0
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): Ubuntu 22.04
#- CUDA/cuDNN version: 11.7
#- GPU models and configuration: GTX 1080Ti
#- How you installed Lightning(`conda`, `pip`, source): pip within conda environment
```

</details>

### More info

in trainer.py:
```python
    @property
    def log_dir(self) -> Optional[str]:
        """The directory for the current experiment. Use this to save images to, etc...

        .. code-block:: python

            def training_step(self, batch, batch_idx):
                img = ...
                save_img(img, self.trainer.log_dir)
        """
        if len(self.loggers) > 0:
            if not isinstance(self.loggers[0], TensorBoardLogger):
                dirpath = self.loggers[0].save_dir
            else:
                dirpath = self.loggers[0].log_dir
        else:
            dirpath = self.default_root_dir

        dirpath = self.strategy.broadcast(dirpath)  # <--- I suspect this line to be the problem
        return dirpath
```

**Comment by awaelchli** [comment]
Hi @aRI0U

The broadcast is required, so the `log_dir` must be called by all ranks to guarantee that all processes get the correct directory. The problem is that you have a hook that's decorated with `@rank_zero_only`, then `log_dir` only gets called on rank 0, and that process will wait for other processes to join, forever.

I recommend that you change the code to this:

```py
# 1. Remove rank_zero_only
# @rank_zero_only  
def on_fit_start(self) -> None:
	# 2. access log_dir on all ranks
	log_dir = self.trainer.log_dir
	if self.global_rank == 0:
		# 3. do something only on process 0
			...
```

**Comment by aRI0U** [comment]
Hi @awaelchli,
Thanks a lot for your prompt reply. When I realized that it worked when I commented out `rank_zero_only` I adapted my code as you said, and now it works.

However, the difficulty here is not to change the code but that it was extremely hard to debug the code to understand what the problem was, and I was far from imagining that calling `trainer.log_dir` in `on_fit_start` could make the model freeze after one training step.

At least now there is a reference to the issue somewhere, however since it is very hard to find and to debug, I have two questions:
- Is broadcast absolutely required when calling `trainer.log_dir`, isn't there another way to handle this to prevent this issue?
- If yes, could it be possible to put a flag, a warning, or any clue that could enable someone facing this situation to have an idea where the problem comes from? Otherwise at least it could be helpful to put a warning box in the docs, by chance people could eventually remember having read that this issue exists.

Thanks!

**Comment by awaelchli** [comment]
> Is broadcast absolutely required when calling trainer.log_dir, isn't there another way to handle this to prevent this issue?

Unfortunately yes. Consider this: A logger (e.g. wandb) would generate a log directory with a version number or randomly generated index. How would we propagate this information to all processes so that the logging directory is unique, so all processes see the same? If we didn't broadcast this information from rank 0, the user would get different values returned from `log_dir`, and this could be equally hard to debug IMO. We are always open for suggestions. At the moment it looks like all alternatives would have significant drawbacks too.

> If yes, could it be possible to put a flag, a warning, or any clue that could enable someone facing this situation to have an idea where the problem comes from? 

Detecting a such a desynchronization of processes / hang process is unfortunately not possible, in general unrelated to Lightning. It is an unsolved problem that if solved would definitely alleviate many other pitfalls that users run into with distributed training. Sorry for the disappointing answer here :( I wish there was better news. 

> Otherwise at least it could be helpful to put a warning box in the docs, by chance people could eventually remember having read that this issue exists.

At the very least, we should definitely document this, making it clear you must call `trainer.log_dir` on all ranks. I agree.

**Comment by silverbulletmdc** [comment]
I pretty agree with the author that the training freeze caused by trainer.log_dir is extreamly hard to debug. I don't think the brodcasting for trainer.log_dir is essential. When the training has started, the log_dir for all processes will not change anymore.
